### ISSUE TITLE
no win64 native, npm install fails 

### ISSUE THREAD

**Issue by orenz** [tjanczuk/tripwire#4]
In execution U get : "module.js:485
  process.dlopen(filename, module.exports);"

**Comment by doudounannan** [comment]
Hello,I install n using "npm install -g n" under windows7 64bit,but it appeas errors.
Belows are error messages:

npm ERR! not a package C:\Users\ZHENGM~1\AppData\Local\Temp\npm-10236-a
422281536224-0.18922873586416245\tmp.tgz
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architectu
.13
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program F
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "n"
npm ERR! cwd C:\Users\zhengmeiyu\Downloads\n-master\bin
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code EBADPLATFORM
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\zhengmeiyu\Downloads\n-master\bin\npm-debug.log
npm ERR! not ok code 0

C:\Users\zhengmeiyu\Downloads\n-master\bin>npm install -g n
npm ERR! not a package C:\Users\ZHENGM~1\AppData\Local\Temp\npm-9600-r0
22281617584-0.6475809873081744\tmp.tgz
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architectu
.13
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program F
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "n"
npm ERR! cwd C:\Users\zhengmeiyu\Downloads\n-master\bin
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code EBADPLATFORM
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\zhengmeiyu\Downloads\n-master\bin\npm-debug.log
npm ERR! not ok code 0

Can you help me?
