### ISSUE TITLE
Compile fails on Node 0.11

### ISSUE THREAD

**Issue by ponychicken** [tjanczuk/tripwire#6]
Node 0.12 is not far from being released and the new v8 engine removed some previously deprecated stuff. There's some details on the changes here: http://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/

I tried to fix some of it myself, but I don't really know much about v8, so I didn't get really far. It might still be a valid starting point: https://github.com/ponychicken/tripwire/tree/node11

**Comment by KenanSulayman** [comment]
Node 0.12 will not exist.

**Comment by ponychicken** [comment]
Do you know something that's not common knowledge? Either way the problem is still there on node HEAD, call it 0.12, 1.0 or something else

**Comment by KenanSulayman** [comment]
Node 0.12 is not going to happen. https://iojs.org — io.js (Node) 1.0.0 will be released in the next hours.

**Comment by ponychicken** [comment]
I know about iojs, but that doesn't mean that Joyent will suddenly abandon node. And the problem still persists, it doesn't compile.

**Comment by paulrutter** [comment]
@KenanSulayman Are you going to fix this for Node 0.12? Would be highly appreciated as the module is very handy.

**Comment by KenanSulayman** [comment]
As you might notice, the comment is from January 14th. And indeed, 0.12 came — and it's de-facto just a rebranded 0.11 for the sake of having a release ready on par with iojs 1.X.

I have no relationship with this module nor am I using it. But I'll have a shot at porting it to nan :-)

**Comment by paulrutter** [comment]
Thanks, that would be great :+1:

**Comment by KenanSulayman** [comment]
I started a port to nan, but the v8 intrinsics changed .. by what I have observed I'm certain that current-v8 doesn't really allow to freely terminate the isolated scope of the user. That would render this module deprecated. I'll have a look again when I'm back in the office tomorrow.

**Comment by StrangeWill** [comment]
I have a commit that almost has it working here:

https://github.com/StrangeWill/tripwire/commit/ad3a643518524d7d1849563e47aac292e1d184db

I can successfully terminate the execution of the main process, but the exception is never thrown by the main thread. Code is backwards compatible with 0.10, this is kind of my first foray into v8. Was poking at @KenanSulayman's code hoping they had the remaining pieces but they seem stuck in the same spot (though it didn't makes sense to me to create a new isolation in the new monitor thread and terminate that, so I used the isolation from the main node thread).

Hope I can get this working fully, even though total termination of the thread is technically "good enough for me", the caught exception would be nice.


Excuse me for any poor assumptions made on my part, complete newbie to this.

**Comment by tjanczuk** [comment]
Just shipped tripwire 0.10 with support for Node 0.12.

**Comment by StrangeWill** [comment]
Awesome! Thanks.

**Comment by paulrutter** [comment]
Thanks @tjanczuk !
